Create database DBprueba

create table TM

CREATE TABLE TM_CATEGORIA(
	[CAT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CAT_NOMBRE] [nchar](150) NULL,
	[CAT_OBS] [nchar](150) NULL,
 CONSTRAINT [PK_TM_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[CAT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


  CREATE PROCEDURE SP_I_CATEGORIA_01
  @CAT_ID INT,
  @CAT_NOMBRE VARCHAR(150),
  @CAT_OBS VARCHAR(150) 
  AS 
  BEGIN
  INSERT INTO TM_CATEGORIA
  (CAT_NOMBRE,CAT_OBS)
  VALUES(@CAT_NOMBRE,@CAT_OBS);

  SELECT * FROM TM_CATEGORIA;
  END

  CREATE PROCEDURE SP_U_CATEGORIA_01
  @CAT_ID INT,
  @CAT_NOMBRE VARCHAR(150),
  @CAT_OBS VARCHAR(150) 
  AS 
  BEGIN
  Update TM_CATEGORIA
	set 
	CAT_NOMBRE = @CAT_NOMBRE,
	CAT_OBS = @CAT_OBS
	where CAT_ID = @CAT_ID
  SELECT * FROM TM_CATEGORIA;
  END

  CREATE PROCEDURE SP_D_CATEGORIA_01
  @CAT_ID INT
  AS 
  BEGIN
  delete from TM_CATEGORIA
	where CAT_ID = @CAT_ID
  SELECT * FROM TM_CATEGORIA;
  END
